//! Minimap: the Rust port of the original minimap raster (`client.bm`) drawn over scenes
//! assembled from world blocks must equal the native HUD capture's 512x512 minimap sprites
//! pixel for pixel (`assets/compiled/ui/minimaps/<baseX>-<baseY>-<plane>.png`, generated by the
//! original `client.bm(world, sprite, 4.0, plane, 0, 0, 48, 48)` in the source capture).
//! Door overrides must move the interactive (red) wall mark with the door.

mod common;

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use clubscape_renderer::core::RendererCore;
use clubscape_renderer::palette::Palette;
use clubscape_renderer::scene::minimap::{self, MapScenes, Raster, WallColours};

use common::repo_root;

const REPRODUCE_BLOCKS: &str = "python3 tools/render-assets/export.py --profile blocks (or --profile unpack-blocks <pack.tar>, see blocks.index.json)";

/// Native minimap captures: scene base and the planes the capture recorded.
const REFERENCES: [(i32, i32); 5] = [
    (3200, 3168),
    (3168, 3168),
    (3120, 3240),
    (3048, 3032),
    (3048, 9456),
];

/// The native minimap rasters live with the UI assets (`assets/compiled/ui/minimaps`); a
/// checkout without them can point `CLUBSCAPE_UI_MINIMAPS` at a copy. Missing references fail.
fn reference_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("CLUBSCAPE_UI_MINIMAPS") {
        return PathBuf::from(dir);
    }
    let dir = repo_root().join("assets/compiled/ui/minimaps");
    assert!(
        dir.join("3200-3168-0.png").exists(),
        "native minimap references missing: {} (integrated UI assets) or set CLUBSCAPE_UI_MINIMAPS",
        dir.display()
    );
    dir
}

fn read_png_rgb(path: &Path) -> (u32, u32, Vec<i32>) {
    let decoder = png::Decoder::new(std::io::BufReader::new(
        std::fs::File::open(path).unwrap_or_else(|e| panic!("{}: {e}", path.display())),
    ));
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0; reader.output_buffer_size().unwrap()];
    let info = reader.next_frame(&mut buf).unwrap();
    let channels = info.color_type.samples();
    let mut out = Vec::with_capacity((info.width * info.height) as usize);
    for px in buf[..info.buffer_size()].chunks(channels) {
        out.push((i32::from(px[0]) << 16) | (i32::from(px[1]) << 8) | i32::from(px[2]));
    }
    (info.width, info.height, out)
}

fn write_png_rgb(path: &Path, width: u32, height: u32, rgb: &[i32]) {
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    let mut encoder = png::Encoder::new(std::fs::File::create(path).unwrap(), width, height);
    encoder.set_color(png::ColorType::Rgb);
    encoder.set_depth(png::BitDepth::Eight);
    let mut writer = encoder.write_header().unwrap();
    let bytes: Vec<u8> = rgb
        .iter()
        .flat_map(|p| [(p >> 16) as u8, (p >> 8) as u8, *p as u8])
        .collect();
    writer.write_image_data(&bytes).unwrap();
}

fn core() -> RendererCore {
    let mut core = RendererCore::new(
        Palette::from_chunks(&common::read_asset("palette.bin")).unwrap(),
        1920,
        1080,
    );
    for entry in std::fs::read_dir(repo_root().join("assets/compiled/render/textures")).unwrap() {
        core.add_texture(&std::fs::read(entry.unwrap().path()).unwrap())
            .unwrap();
    }
    core.load_map_scenes(&common::read_asset("minimap/mapscenes.bin"))
        .unwrap();
    core
}

fn load_blocks(core: &mut RendererCore, squares: &[i32]) {
    for &square in squares {
        if !repo_root()
            .join(format!("assets/compiled/render/blocks/{square}.bin"))
            .exists()
        {
            // Squares outside the M1 world stay empty, as unloaded map squares do originally.
            continue;
        }
        core.load_block(
            square,
            &common::read_local_export(&format!("blocks/{square}.bin"), REPRODUCE_BLOCKS),
            &common::read_local_export(&format!("blocks/{square}.models.bin"), REPRODUCE_BLOCKS),
        )
        .unwrap();
        core.load_minimap_block(
            square,
            &common::read_asset(&format!("minimap/blocks/{square}.bin")),
        )
        .unwrap();
    }
}

fn surface_rgb(surface: &clubscape_renderer::core::MinimapSurface) -> Vec<i32> {
    surface
        .rgba
        .chunks(4)
        .map(|p| (i32::from(p[0]) << 16) | (i32::from(p[1]) << 8) | i32::from(p[2]))
        .collect()
}

#[test]
fn map_scenes_load_with_the_original_shape_masks() {
    let assets = MapScenes::from_chunks(&common::read_asset("minimap/mapscenes.bin")).unwrap();
    assert_eq!(assets.shapes[0], 0);
    assert_eq!(assets.shapes[1], -1);
    assert!(
        assets.sprites.len() >= 100,
        "map-scene sprite set is {} sprites",
        assets.sprites.len()
    );
    assert!(assets.sprites.iter().all(|s| s.width >= 0 && s.height >= 0));
    // Every non-trivial shape mask has both covered and uncovered cells.
    for (i, &mask) in assets.shapes.iter().enumerate().skip(2).take(11) {
        assert!(
            mask != 0 && mask != -1,
            "shape {i} mask {mask:#x} is degenerate"
        );
    }
}

#[test]
fn minimap_reports_missing_inputs_explicitly() {
    let mut core = RendererCore::new(
        Palette::from_chunks(&common::read_asset("palette.bin")).unwrap(),
        640,
        480,
    );
    let err = core.minimap_surface().unwrap_err().to_string();
    assert!(err.contains("no scene"), "{err}");
    assert!(
        MapScenes::from_chunks(b"garbage").is_err(),
        "corrupt map-scene asset must be rejected"
    );
    assert!(
        core.load_minimap_block(12850, b"garbage").is_err(),
        "corrupt sidecar must be rejected"
    );
    // A sidecar registered under the wrong square is refused.
    let sidecar = common::read_asset("minimap/blocks/12850.bin");
    assert!(core.load_minimap_block(12849, &sidecar).is_err());
}

#[test]
fn terrain_fill_matches_the_original_shape_sampling() {
    // A shape-1 (full overlay) tile fills its whole box with the overlay; shape 0 with underlay.
    let assets = MapScenes::from_chunks(&common::read_asset("minimap/mapscenes.bin")).unwrap();
    let mut scene = clubscape_renderer::scene::SceneData::empty_grid(
        "t".into(),
        3200,
        3168,
        184,
        4,
        40,
        104,
        4 << 16,
    );
    let index = scene.tile_index(0, 40, 40);
    scene.flags[index] = 1;
    scene.paints.insert(
        index,
        clubscape_renderer::scene::TilePaint {
            sw: 0,
            se: 0,
            ne: 0,
            nw: 0,
            texture: -1,
            flat: true,
            rgb: 0x123456,
        },
    );
    let mut raster = Raster::new(512, 512);
    let stats = minimap::render(
        &scene,
        0,
        &assets,
        WallColours::REFERENCE,
        &HashMap::new(),
        4.0,
        (0, 0),
        (48, 48),
        &mut raster,
    )
    .unwrap();
    assert_eq!(stats.terrain_tiles, 1);
    // Tile (0,0) occupies raster x 48..52, y 460..464 (rows from the bottom margin).
    for y in 460..464 {
        for x in 48..52 {
            assert_eq!(raster.pixels[(y * 512 + x) as usize], 0x123456, "({x},{y})");
        }
    }
    assert_eq!(raster.pixels[(459 * 512 + 48) as usize], 1);
    assert_eq!(raster.pixels[(460 * 512 + 52) as usize], 1);
    let (rgba, mask) = minimap::to_rgba(&raster);
    assert_eq!(mask.iter().filter(|&&m| m == 1).count(), 16);
    assert_eq!(
        &rgba[(460 * 512 + 48) * 4..(460 * 512 + 48) * 4 + 4],
        &[0x12, 0x34, 0x56, 255]
    );
}

/// Tiles within this many tiles of the 104x104 scene edge: the original loader blends their
/// floor colours from inputs that depend on the scene base, so a scene assembled from
/// pre-blended blocks reproduces them only approximately (see README, "Known deviations").
const EDGE_BAND: i32 = 5;

/// Every native minimap capture (5 scenes x 3 planes) must be reproduced exactly from the
/// world blocks and the minimap sidecars over the scene interior (tiles 5..98): terrain
/// colours and shapes, wall/door/diagonal marks, map-scene sprites and bridge tiles. Edge-band
/// differences are counted and must stay confined to the band. Needs the block exports.
#[test]
#[ignore = "needs the local world block exports (export.py --profile blocks)"]
fn assembled_minimaps_equal_the_native_captures() {
    let references = reference_dir();
    let out_dir = repo_root().join(".local/render-assets/test-output/minimap");
    let mut report = Vec::new();
    let mut failures = Vec::new();
    for (bx, by) in REFERENCES {
        let mut core = core();
        load_blocks(&mut core, &RendererCore::squares_for_base(bx, by));
        core.assemble_scene(bx, by, false, 0.0).unwrap();
        for plane in 0..3 {
            let name = format!("{bx}-{by}-{plane}");
            let reference = references.join(format!("{name}.png"));
            let (w, h, expected) = read_png_rgb(&reference);
            assert_eq!((w, h), (512, 512), "{name}: reference size");
            core.set_plane(plane);
            let surface = core.minimap_surface().unwrap().clone();
            assert!(
                surface.complete,
                "{name}: unresolved placements {:?}",
                surface.stats.notes
            );
            assert_eq!((surface.width, surface.height), (512, 512));
            assert_eq!(
                (surface.base_x, surface.base_y, surface.plane),
                (bx, by, plane)
            );
            let actual = surface_rgb(&surface);
            let mut interior = Vec::new();
            let mut band = 0usize;
            for i in 0..actual.len() {
                if actual[i] == expected[i] {
                    continue;
                }
                let (px, py) = ((i % 512) as i32, (i / 512) as i32);
                let (tx, ty) = ((px - 48).div_euclid(4), (464 - py - 1).div_euclid(4));
                if (EDGE_BAND..104 - EDGE_BAND).contains(&tx)
                    && (EDGE_BAND..104 - EDGE_BAND).contains(&ty)
                {
                    interior.push(i);
                } else {
                    band += 1;
                }
            }
            write_png_rgb(
                &out_dir.join(format!("{name}-candidate.png")),
                512,
                512,
                &actual,
            );
            if !interior.is_empty() || band > 0 {
                let diff: Vec<i32> = (0..actual.len())
                    .map(|i| {
                        if actual[i] != expected[i] {
                            0xFF0000
                        } else {
                            0x202020
                        }
                    })
                    .collect();
                write_png_rgb(&out_dir.join(format!("{name}-diff.png")), 512, 512, &diff);
            }
            if let Some(&first) = interior.first() {
                failures.push(format!(
                    "{name}: {} interior pixels differ (first at {},{}: candidate {:06x} reference {:06x})",
                    interior.len(),
                    first % 512,
                    first / 512,
                    actual[first],
                    expected[first]
                ));
            }
            report.push(format!(
                "{name}: interior_mismatches={} edge_band_mismatches={} terrain={} walls={} diagonals={} mapscenes={} icons={}",
                interior.len(),
                band,
                surface.stats.terrain_tiles,
                surface.stats.wall_marks,
                surface.stats.diagonal_marks,
                surface.stats.map_scenes,
                surface.icons.len()
            ));
        }
    }
    std::fs::create_dir_all(&out_dir).unwrap();
    std::fs::write(out_dir.join("report.txt"), report.join("\n") + "\n").unwrap();
    assert!(
        failures.is_empty(),
        "minimap interior mismatches:\n{}",
        failures.join("\n")
    );
}

/// A door state changes the wall config the minimap draws: the red interactive mark follows
/// the door's rotation and the surface revision advances; identical state reuses the cache.
#[test]
#[ignore = "needs the local world block exports (export.py --profile blocks)"]
fn door_states_move_the_minimap_wall_mark() {
    let (bx, by) = (3200, 3168);
    let mut core = core();
    load_blocks(&mut core, &RendererCore::squares_for_base(bx, by));
    core.assemble_scene(bx, by, false, 0.0).unwrap();
    // Find an interactive straight wall (a door) on plane 0 in the main area.
    let scene = core.scene().unwrap();
    let mut door = None;
    for x in 0..104 {
        for y in 0..104 {
            let index = scene.tile_index(0, x + scene.offset, y + scene.offset);
            if let Some(wall) = scene.walls.get(&index)
                && wall.config & 31 == 0
                && !clubscape_renderer::scene::tag_non_interactive(wall.hash)
            {
                door = Some((bx + x, by + y, wall.config >> 6 & 3, wall.hash));
                break;
            }
        }
        if door.is_some() {
            break;
        }
    }
    let (dx, dy, rotation, hash) = door.expect("an interactive door wall in Lumbridge");
    let object = clubscape_renderer::scene::tag_object_id(hash);
    let closed = core.minimap_surface().unwrap().clone();
    let again = core.minimap_surface().unwrap().clone();
    assert_eq!(
        closed.revision, again.revision,
        "unchanged state reuses the cached surface"
    );
    let turned = (rotation + 1) & 3;
    let view = format!(
        r#"{{"revision":"1","tick":"1","player":{{"id":"p","tile":{{"x":{dx},"y":{dy},"plane":0}}}},
        "entities":[],"groundItems":[],"dynamicObjects":[{{"id":"d","sourceId":{object},
        "tile":{{"x":{dx},"y":{dy},"plane":0}},"doorOpen":true,"quarterTurns":{turned}}}]}}"#
    );
    core.update_world(&view, 0.0).unwrap();
    let open = core.minimap_surface().unwrap().clone();
    assert!(open.revision > closed.revision);
    let closed_rgb = surface_rgb(&closed);
    let open_rgb = surface_rgb(&open);
    // The tile's 4x4 box: raster x 48 + (dx-bx)*4, y 512 - 48 - (dy-by+1)*4.
    let x0 = 48 + (dx - bx) * 4;
    let y0 = 512 - 48 - (dy - by + 1) * 4;
    let red = |rgb: &[i32]| -> Vec<(i32, i32)> {
        let mut out = Vec::new();
        for y in y0..y0 + 4 {
            for x in x0..x0 + 4 {
                if rgb[(y * 512 + x) as usize] == WallColours::REFERENCE.interactive {
                    out.push((x - x0, y - y0));
                }
            }
        }
        out
    };
    let before = red(&closed_rgb);
    let after = red(&open_rgb);
    assert!(!before.is_empty(), "closed door draws a red wall mark");
    assert!(!after.is_empty(), "open door draws a red wall mark");
    assert_ne!(before, after, "the mark moved with the door rotation");
    let differing = closed_rgb
        .iter()
        .zip(&open_rgb)
        .filter(|(a, b)| a != b)
        .count();
    assert!(
        differing <= 8,
        "only the door tile changed ({differing} pixels)"
    );
}
