#!/usr/bin/env python3
"""Generate only data projections of the separately pinned native calibration."""

import hashlib
import json
from pathlib import Path


def main():
    base = Path("research/browser-audio-policy")
    objects = json.loads((base / "native-objects.json").read_text())["cases"][0]
    geography = json.loads((base / "music-geography.json").read_text())
    catalogue = json.loads((base / "native-catalog.json").read_text())["cases"]
    music = next(c for c in catalogue if c["case"] == "original-music-table44-and-area-group128")
    rows = {}
    for record in music["selected_rows"] + music["same_area_rows"]:
        row = record["definition"]
        values = row["columnValues"]
        rows[values[4][0]] = {
            "group": values[4][0], "row": row["id"], "name": values[1][0],
            "durationTicks": values[3][0], "area": values[7][0] if values[7] else None,
            "defaultArea": bool(values[8]), "sourceSha256": record["source_sha256"],
        }
    pcm = json.loads((base / "native-pcm.json").read_text())
    comparisons = next(c["observed"] for c in pcm["cases"] if c["case"] == "immutable128-pcm-native255-mixer-comparison")
    sources = ["native-objects.json", "native-catalog.json", "music-geography.json", "native-pcm.json"]
    locks = {name: hashlib.sha256((base/name).read_bytes()).hexdigest() for name in sources}
    definitions = [{k:v for k,v in entry.items() if k != "source_sha256"} for entry in objects["definitions"]]
    data = {
        "calibrationInputs": locks, "objects": definitions, "varbits": objects["varbits"],
        "music": list(rows.values()), "geography": geography["areas"],
        "nativeMixComparisons": comparisons,
    }
    Path("web/audio/native-data.ts").write_text(
        "// Generated by tools/browser-audio-tests/native/generate_policy.py from actual source evidence.\n"
        "export const NATIVE_AUDIO_DATA = " + json.dumps(data, separators=(",", ":")) + " as const;\n")
    requirements = []
    for group in [64,327,163,145]:
        row = rows[group]
        requirements.append({
            "kind": "missing_original_track", "index": 6, "group": group,
            "native_music_row": row["row"], "name": row["name"],
            "native_row_sha256": row["sourceSha256"], "native_area": 1,
            "reason": "Native table44 Modern Lumbridge membership; no approved playable publication exists.",
        })
    rendered = pcm["cases"][0]["observed"]
    for value in comparisons:
        if not value["additional_clip_samples"]:
            continue
        target = next(v for v in rendered if v["index"] == value["index"] and v["group"] == value["group"] and v["volume"] == 255)
        original = next(v for v in rendered if v["index"] == value["index"] and v["group"] == value["group"] and v["volume"] == 128)
        requirements.append({
            "kind": "native_mixer_representation", "index": value["index"], "group": value["group"],
            "native_volume": 255, "unchanged_128_pcm_sha256": original["pcm_s16le_sha256"],
            "required_native_255_pcm_sha256": target["pcm_s16le_sha256"], "frames": target["frames"],
            "source_native_clip_samples": target["native_device_clipped_samples"],
            "additional_clips_if_scaling_current_file": value["additional_clip_samples"],
            "reason": "Do not modify frozen files or add a limiter/normalization; provide original native-level representation or dynamic original synthesis.",
        })
    (base / "publication-needs.json").write_text(json.dumps({
        "schema_version": 1,
        "source_pack_sha256": "b62e19704e17d3d3e4e819f803ef49ba7cc54034ae407184b423427c65d9674d",
        "frozen_source_files_modified": False, "requirements": requirements, "calibration_inputs": locks,
        "bridge_contract": "web/audio/native-scene.ts: SourceAudioScene, SourceMusicSelector; web/audio/README.md",
        "acceptance": False,
    }, indent=2) + "\n")
    print(f"Generated {len(definitions)} native objects, {len(rows)} music rows and three source map families.")


if __name__ == "__main__":
    main()
