[package]
name = "clubscape-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
clubscape-game-types.workspace = true
prost.workspace = true
thiserror.workspace = true
uuid.workspace = true

[build-dependencies]
prost-build = "0.14"
protoc-bin-vendored = "3"

[lints]
workspace = true
